version: '3'
services:
    php:
        build:
            context: ./docker/php
        depends_on:
            - db
        container_name: app
        restart: unless-stopped
        tty: true
        ports:
            - 9000:9000
        volumes:
            - ./:/srv/www/app
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        environment:
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
    nginx:
        image: nginx:1.13.8
        ports:
            - 80:80
        volumes:
            - ./:/srv/www/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
    db:
        image: mysql:5.7
        restart: always
        ports:
            - 3308:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports:
            - 8888:80
        environment:
            PMA_HOST: db
