version: '3'
services:
    php:
        build:
            context: ./docker/php
        container_name: app
        restart: unless-stopped
        tty: true
        ports:
            - 9000:9000
        volumes:
            - ./:/srv/www/app
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            SERVICE_NAME: app
            SERVICE_TAGS: dev
    nginx:
        image: nginx:1.13.8
        ports:
            - 80:80
        volumes:
            - ./:/srv/www/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    mysql:
        image: mysql:5.7
        ports:
            - 3307:3306
        depends_on:
            - php
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
